name: Test and Deploy
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
          
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Dependencies
        run: |
          sudo pip3 install gunicorn==20.0.4
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Lint with pycodestyle
        run: |
          pycodestyle --first *.py

      - name: Test with pytest
        run: |
          python3 -m pytest
